Repository kubernetes-sigs/promo-tools, pull requests merged in 2019-03, with the labels that each got.

#25 Complete migration to kubernetes-sigs
  OWNERS
  SECURITY_CONTACTS
  code-of-conduct.md
Labels: cncf-cla: yes, size/M

#23 add script to invoke the promoter against multiple manifests
  BUILD.bazel
  util/multirun.sh
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M

#28 update Go imports to use kubernetes-sigs
  BUILD.bazel
  README.md
  cip.go
  cloudbuild.yaml
  lib/container/BUILD.bazel
  lib/dockerregistry/BUILD.bazel
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
  lib/dockerregistry/set.go
  lib/dockerregistry/types.go
  lib/json/BUILD.bazel
  lib/stream/BUILD.bazel
  util/multirun.sh
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M

#29 add '-no-service-account' flag
  cip.go
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
  lib/dockerregistry/types.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#30 cleanup comments
  lib/dockerregistry/inventory_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#31 allow promoting to multiple repositories
  README.md
  cip.go
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
  lib/dockerregistry/types.go
  util/multirun.sh
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XXL

#34 Fixes incorrect manifest example from readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#32 make multirun.sh aware of changed manifest files (only run on changed files)
  cip.go
  lib/dockerregistry/inventory.go
  lint.sh
  util/multirun.sh
  workspace_status.sh
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L
