Repository kubernetes-sigs/promo-tools, pull requests merged in 2019-10, with the labels that each got.

#139 remove renames feature
  .golangci.yml
  cip.go
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/invalid/overlapping-destination-vertices-different-digest-by-rename/a/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/invalid/overlapping-destination-vertices-different-digest-by-rename/b/manifest.yaml
  lib/dockerregistry/types.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#140 remove dead code for renames
  README.md
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
  lib/dockerregistry/inventory_test/TestParseManifestsFromDir/basic/a/manifest.yaml
  lib/dockerregistry/inventory_test/TestParseManifestsFromDir/basic/b/c/manifest.yaml
  lib/dockerregistry/inventory_test/TestParseManifestsFromDir/basic/b/manifest.yaml
  lib/dockerregistry/inventory_test/TestParseManifestsFromDir/basic/manifest.yaml
  lib/dockerregistry/inventory_test/TestParseManifestsFromDir/singleton/a/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/invalid/overlapping-destination-vertices-different-digest/a/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/invalid/overlapping-destination-vertices-different-digest/b/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/invalid/overlapping-renames-across-manifests/a/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/invalid/overlapping-renames-across-manifests/b/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/invalid/overlapping-renames-invalid-manifest/a/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/invalid/overlapping-renames-invalid-manifest/b/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/valid/overlapping-destination-vertices-same-digest-by-rename/a/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/valid/overlapping-destination-vertices-same-digest-by-rename/b/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/valid/overlapping-destination-vertices-same-digest/a/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/valid/overlapping-destination-vertices-same-digest/b/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/valid/overlapping-src-registries/a/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/valid/overlapping-src-registries/b/manifest.yaml
  lib/dockerregistry/types.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XL

#141 add -thin-manifest-dir flag
  README.md
  cip.go
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
  lib/dockerregistry/inventory_test/TestParseManifestsFromDir/basic-thin/images/a.yaml
  lib/dockerregistry/inventory_test/TestParseManifestsFromDir/basic-thin/images/b.yaml
  lib/dockerregistry/inventory_test/TestParseManifestsFromDir/basic-thin/images/bc.yaml
  lib/dockerregistry/inventory_test/TestParseManifestsFromDir/basic-thin/images/root.yaml
  lib/dockerregistry/inventory_test/TestParseManifestsFromDir/basic-thin/thin-manifests/a/promoter-manifest.yaml
  lib/dockerregistry/inventory_test/TestParseManifestsFromDir/basic-thin/thin-manifests/b/c/promoter-manifest.yaml
  lib/dockerregistry/inventory_test/TestParseManifestsFromDir/basic-thin/thin-manifests/b/promoter-manifest.yaml
  lib/dockerregistry/inventory_test/TestParseManifestsFromDir/basic-thin/thin-manifests/promoter-manifest.yaml
  lib/dockerregistry/inventory_test/TestParseManifestsFromDir/basic/a/promoter-manifest.yaml
  lib/dockerregistry/inventory_test/TestParseManifestsFromDir/basic/b/c/promoter-manifest.yaml
  lib/dockerregistry/inventory_test/TestParseManifestsFromDir/basic/b/promoter-manifest.yaml
  lib/dockerregistry/inventory_test/TestParseManifestsFromDir/basic/promoter-manifest.yaml
  lib/dockerregistry/inventory_test/TestParseManifestsFromDir/multiple-rebases/a/promoter-manifest.yaml
  lib/dockerregistry/inventory_test/TestParseManifestsFromDir/multiple-rebases/b/promoter-manifest.yaml
  lib/dockerregistry/inventory_test/TestParseManifestsFromDir/singleton/a/promoter-manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/invalid/overlapping-destination-vertices-different-digest/a/promoter-manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/invalid/overlapping-destination-vertices-different-digest/b/promoter-manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/valid/overlapping-destination-vertices-same-digest/a/promoter-manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/valid/overlapping-destination-vertices-same-digest/b/promoter-manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/valid/overlapping-src-registries/a/promoter-manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/valid/overlapping-src-registries/b/promoter-manifest.yaml
  lib/dockerregistry/types.go
  test-e2e/fixture/recursive-thin/images/bar/images.yaml
  test-e2e/fixture/recursive-thin/images/foo/images.yaml
  test-e2e/fixture/recursive-thin/manifests/bar/promoter-manifest.yaml
  test-e2e/fixture/recursive-thin/manifests/foo/promoter-manifest.yaml
  test-e2e/fixture/recursive/bar/promoter-manifest.yaml
  test-e2e/fixture/recursive/foo/promoter-manifest.yaml
  test-e2e/fixture/sanity/promoter-manifest.yaml
  test-e2e/tests.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#142 ParseManifestsFromDir: improve filename handling
  lib/dockerregistry/inventory.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#146 add gcloud fallback creds for go-containerregistry
  BUILD.bazel
  docker/config.json
  test-e2e/e2e-entrypoint-from-container.sh
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M

#147 fix golint error
  lib/dockerregistry/inventory.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/release, size/XS

#149 README: remove references to src-registry
  README.md
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S
