Repository kubernetes-sigs/promo-tools, pull requests merged in 2019-08, with the labels that each got.

#83 BackoffDefault: increase default timeout
  lib/dockerregistry/inventory.go
  lib/stream/types.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#81 remove -garbage-collect and -delete-extra-tags flags
  README.md
  cip.go
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
  lib/dockerregistry/types.go
  test/e2e.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#84 misc fixes
  .gitignore
  .golangci.yml
  Makefile
  WORKSPACE
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
  test-e2e/BUILD.bazel
  test-e2e/README.md
  test-e2e/e2e.go
  test-e2e/e2e.sh
  test-e2e/golden/linux_amd64.txt
  test-e2e/golden/linux_s390x.txt
  test-e2e/tests.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#85 Misc fixes
  cip.go
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
  lib/stream/BUILD.bazel
  lib/stream/http.go
  lib/stream/types.go
  test-e2e/e2e.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M

#48 Promotion for non-container artifacts
  README.md
  cmd/promobot-files/README.md
  cmd/promobot-files/main.go
  go.mod
  go.sum
  lib/dockerregistry/inventory.go
  lib/dockerregistry/types.go
  pkg/api/files/manifest.go
  pkg/api/files/manifest_test.go
  pkg/api/files/validation.go
  pkg/cmd/promotefiles.go
  pkg/filepromoter/file.go
  pkg/filepromoter/filestore.go
  pkg/filepromoter/gcs.go
  pkg/filepromoter/interfaces.go
  pkg/filepromoter/manifest.go
  pkg/filepromoter/token.go
  pkg/gcloud/token.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XXL

#86 Recursive manifests
  cip.go
  cloudbuild.yaml
  cmd/promobot-files/BUILD.bazel
  lib/dockerregistry/BUILD.bazel
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
  lib/dockerregistry/inventory_test/TestParseManifestsFromDir/basic/a/manifest.yaml
  lib/dockerregistry/inventory_test/TestParseManifestsFromDir/basic/b/c/manifest.yaml
  lib/dockerregistry/inventory_test/TestParseManifestsFromDir/basic/b/manifest.yaml
  lib/dockerregistry/inventory_test/TestParseManifestsFromDir/basic/manifest.yaml
  lib/dockerregistry/inventory_test/TestParseManifestsFromDir/empty/non-manifest.txt
  lib/dockerregistry/inventory_test/TestParseManifestsFromDir/singleton/a/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/invalid/different-dst-registries/a/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/invalid/different-dst-registries/b/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/invalid/different-dst-registry-creds/a/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/invalid/different-dst-registry-creds/b/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/invalid/empty
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/invalid/overlapping-renames-across-manifests/a/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/invalid/overlapping-renames-across-manifests/b/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/invalid/overlapping-renames-invalid-manifest/a/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/invalid/overlapping-renames-invalid-manifest/b/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/invalid/overlapping-src-registries/a/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/invalid/overlapping-src-registries/b/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/valid/basic
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/valid/singleton
  lib/dockerregistry/types.go
  lib/stream/http.go
  pkg/api/files/BUILD.bazel
  pkg/cmd/BUILD.bazel
  pkg/filepromoter/BUILD.bazel
  pkg/gcloud/BUILD.bazel
  test-e2e/e2e.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XXL

#87 Optimized reads
  cip.go
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
  test-e2e/e2e.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#91 some tweaks to the e2e tests and also bazel updates
  Makefile
  WORKSPACE
  go.mod
  go.sum
  test-e2e/BUILD.bazel
  test-e2e/e2e.go
  test-e2e/e2e.sh
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XL

#88 file promoter: use json tags
  pkg/api/files/manifest.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#92 misc fixes/changes
  Makefile
  WORKSPACE
  go.mod
  go.sum
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
  lib/dockerregistry/inventory_test/TestParseManifestsFromDir/multiple-rebases/a/manifest.yaml
  lib/dockerregistry/inventory_test/TestParseManifestsFromDir/multiple-rebases/b/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/invalid/different-dst-registry-creds/a/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/invalid/different-dst-registry-creds/b/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/valid/multiple-rebases
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XL

#93 e2e test: add test case for testing the new "-manifest-dir" flag (recursive manifests)
  Makefile
  test-e2e/BUILD.bazel
  test-e2e/e2e.go
  test-e2e/fixture/recursive/bar/manifest.yaml
  test-e2e/fixture/recursive/foo/manifest.yaml
  test-e2e/fixture/sanity/manifest.yaml
  test-e2e/golden/bar/1.0
  test-e2e/golden/foo/1.0-linux_amd64
  test-e2e/golden/foo/1.0-linux_s390x
  test-e2e/golden/linux_amd64.txt
  test-e2e/golden/linux_s390x.txt
  test-e2e/tests.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#89 Set crc32c when uploading to GCS
  pkg/filepromoter/gcs.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#98 add e2e testing entrypoint (to be run from within a container in Prow)
  Makefile
  test-e2e/e2e-entrypoint-from-container.sh
  test-e2e/e2e.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M

#99 Makefile: bazel: explicitly enable stamping
  Makefile
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#100 cip: add service account activation logic
  BUILD.bazel
  cip.go
  pkg/gcloud/BUILD.bazel
  pkg/gcloud/token.go
  test-e2e/BUILD.bazel
  test-e2e/e2e.go
  tools/bazel_get_workspace_status
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M

#101 do not exit prematurely when using -manifest-dir
  cip.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#103 remove dead code
  util/multirun.sh
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#104 bazel: remove dead code
  BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#102 OWNERS: add ps882 as reviewer
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#105 use new staging repo name
  lib/dockerregistry/inventory.go
  pkg/cmd/promotefiles.go
  pkg/filepromoter/file.go
  pkg/filepromoter/filestore.go
  pkg/filepromoter/manifest.go
  workspace_status.sh
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#106 SplitByKnownRegistries: sort names for determinism
  lib/dockerregistry/inventory.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#107 update Readme.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#108 lint: download go dependencies
  lib/dockerregistry/inventory.go
  lint.sh
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#109 cip: print version information during promotion
  cip.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#110 bugfix for sorting RegistryContexts
  lib/dockerregistry/inventory.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#111 simplify linting logic
  Makefile
  lint.sh
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M

#112 MkReadRepositoryCmdReal: condition addition of Bearer auth creds
  lib/dockerregistry/inventory.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#116 e2e: pass --stamp flag to bazel
  test-e2e/e2e.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS
