Repository kubernetes-sigs/promo-tools, pull requests merged in 2019-09, with the labels that each got.

#125 Fix linter
  .golangci.yml
  lib/dockerregistry/inventory.go
  pkg/filepromoter/filestore.go
  test-e2e/e2e.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#123 workspace_status: use Mac-friendly arguments to 'date'
  workspace_status.sh
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#126 mkPopulateRequestsForPromotionEdges: clean up duplicate statements
  lib/dockerregistry/inventory.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#127 bazel: update dependencies
  WORKSPACE
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#122 Improve README
  README.md
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#131 use crane.Copy for copying images
  lib/dockerregistry/BUILD.bazel
  lib/dockerregistry/inventory.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#129 Tighten up set description
  README.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, sig/release, size/S

#132 Manifest validation
  cip.go
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/invalid/overlapping-destination-vertices-different-digest-by-rename/a/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/invalid/overlapping-destination-vertices-different-digest-by-rename/b/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/invalid/overlapping-destination-vertices-different-digest/a/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/invalid/overlapping-destination-vertices-different-digest/b/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/valid/overlapping-destination-vertices-same-digest-by-rename/a/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/valid/overlapping-destination-vertices-same-digest-by-rename/b/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/valid/overlapping-destination-vertices-same-digest/a/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/valid/overlapping-destination-vertices-same-digest/b/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/valid/overlapping-src-registries/a/manifest.yaml
  lib/dockerregistry/inventory_test/TestValidateManifestsFromDir/valid/overlapping-src-registries/b/manifest.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#133 misc fixes
  cip.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#134 allow using the promoter for diffing GCR contents
  .golangci.yml
  cip.go
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
  lib/dockerregistry/types.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XL

#135 refer to manifest lists by their digest
  lib/dockerregistry/inventory.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#136 add -flattened-snapshot flag
  cip.go
  lib/dockerregistry/inventory.go
  lib/dockerregistry/types.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M

#137 misc cleanups
  cip.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S
