Repository kubernetes-sigs/promo-tools, pull requests merged in 2019-07, with the labels that each got.

#62 basic e2e testing framework
  Makefile
  WORKSPACE
  cip.go
  lib/dockerregistry/BUILD.bazel
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
  lib/dockerregistry/types.go
  test/BUILD.bazel
  test/README.md
  test/e2e.go
  test/e2e.sh
  test/golden/linux_amd64.txt
  test/golden/linux_s390x.txt
  test/tests.yaml
  tools/bazel_get_workspace_status
  workspace_status.sh
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XL

#66 Add --snapshot-tag flag: only output items with the specified tag
  cip.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#67 Migrate logging to klog (rebased)
  cip.go
  lib/dockerregistry/inventory.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M

#73 update service account for staging registry
  test/tests.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#80 do not promote images that could not be read properly
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
  lib/dockerregistry/types.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#79 bazel: allow building from NixOS
  WORKSPACE
  tools/go_sdk/BUILD
  tools/go_sdk/WORKSPACE
  tools/go_sdk/sdk.bzl
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M
