Repository kubernetes-sigs/promo-tools, pull requests merged in 2019-05, with the labels that each got.

#44 Change imports to use sigs.k8s.io vanity URL
  BUILD.bazel
  README.md
  cip.go
  cloudbuild.yaml
  go.mod
  lib/container/BUILD.bazel
  lib/dockerregistry/BUILD.bazel
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
  lib/dockerregistry/set.go
  lib/dockerregistry/types.go
  lib/json/BUILD.bazel
  lib/stream/BUILD.bazel
  util/multirun.sh
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M

#45 Rename bytes variables to b
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#46 Explicitly tag all yaml fields that are serialized
  lib/dockerregistry/types.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#47 Switch to k8s-standard SCRIPT_ROOT approach
  lint.sh
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#35 Added --gen-images flag
  Gopkg.lock
  cip.go
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#50 Extract logic to get token for ServiceAccount to its own function
  lib/dockerregistry/inventory.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M

#52 Undo search/replace error
  util/multirun.sh
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#51 Simplify gcloud execution
  lib/dockerregistry/inventory.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M

#53 Replace log with klog
  cip.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S
