Repository kubernetes-sigs/promo-tools, pull requests merged in 2020-03, with the labels that each got.

#187 Fix auditor
  BUILD.bazel
  cip.go
  lib/audit/auditor.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#189 fix SplitByKnownRegistries
  cip.go
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M

#192 promobot-generate-manifest: Fix name of bazel target
  cmd/promobot-generate-manifest/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#193 Fix auditor
  lib/audit/BUILD.bazel
  lib/audit/auditor.go
  lib/audit/types.go
  lib/dockerregistry/inventory.go
  lib/logclient/BUILD.bazel
  lib/logclient/fake.go
  lib/logclient/gcp.go
  lib/logclient/types.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#194 address review comments from #193
  lib/audit/auditor.go
  lib/logclient/fake.go
  lib/logclient/gcp.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M

#195 convert LoggingFacility from a struct to an interface
  lib/audit/auditor.go
  lib/audit/types.go
  lib/logclient/fake.go
  lib/logclient/gcp.go
  lib/logclient/types.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#197 gcp error reporting: clarify error
  lib/report/gcp.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#198 ServerContext: use a RemoteManifestFacility wrapper for cloning
  lib/audit/BUILD.bazel
  lib/audit/auditor.go
  lib/audit/types.go
  lib/remotemanifest/BUILD.bazel
  lib/remotemanifest/fake.go
  lib/remotemanifest/git.go
  lib/remotemanifest/types.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#199 fix child manifest handling
  cip.go
  lib/audit/BUILD.bazel
  lib/audit/auditor.go
  lib/audit/auditor_test.go
  lib/audit/types.go
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
  lib/dockerregistry/types.go
  lib/logclient/fake.go
  lib/logclient/types.go
  lib/report/fake.go
  test-e2e/cip-auditor/tests.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XL

#200 add more tests to the auditor
  .gitignore
  lib/audit/auditor.go
  lib/audit/auditor_test.go
  lib/dockerregistry/inventory.go
  lib/dockerregistry/types.go
  test-e2e/cip-auditor/cip-auditor-e2e.go
  test-e2e/cip-auditor/fixture/fatManifest-subproject-different-prefix/images/foo/images.yaml
  test-e2e/cip-auditor/fixture/fatManifest-subproject-different-prefix/manifests/foo/promoter-manifest.yaml
  test-e2e/cip-auditor/tests.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#205 SplitByKnownRegistries: ensure clean split
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#206 make logging more verbose
  lib/audit/auditor.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS
