Repository kubernetes-sigs/promo-tools, pull requests merged in 2020-06, with the labels that each got.

#217 Using .bazelrc instead of BAZEL_BUILD_OPTS in Makefile
  .bazelrc
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/release, size/S

#218 Added new Make target for testing on Mac
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/release, size/XS

#219 Exiting with error if any errors are encountered in the promotion step
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/release, size/L

#210 Add manifest edit command
  .bazelrc
  BUILD.bazel
  Makefile
  WORKSPACE
  cip.go
  cmd/cip-mm/BUILD.bazel
  cmd/cip-mm/README.md
  cmd/cip-mm/main.go
  lib/dockerregistry/BUILD.bazel
  lib/dockerregistry/grow_manifest.go
  lib/dockerregistry/grow_manifest_test.go
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
  lib/dockerregistry/inventory_test/TestFindManifest/empty
  lib/dockerregistry/inventory_test/TestFindManifest/singleton
  lib/dockerregistry/types.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XL

#221 Removed unused 'verbosity' flag from the promoter
  cip.go
  lib/audit/auditor.go
  lib/dockerregistry/grow_manifest.go
  lib/dockerregistry/inventory.go
  lib/dockerregistry/types.go
  test-e2e/cip-auditor/cip-auditor-e2e.go
  test-e2e/cip/e2e.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/release, size/S

#222 Added a PreCheck Interface for adding future checks against pull requests
  cip.go
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
  lib/dockerregistry/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/release, size/M

#229 added --timeout option to make lint
  Makefile
Labels: cncf-cla: yes, needs-ok-to-test, sig/release, size/XS

#231 increased timeout of golangci-lint and added verbosity flag
  Makefile
Labels: cncf-cla: yes, needs-ok-to-test, sig/release, size/XS

#224 WIP: Adding a JSON Summary for Promoter
  cip.go
  lib/dockerregistry/inventory.go
  lib/dockerregistry/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/release, size/S

#232 adding checks-interface explanation readme
  checks_interface.md
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#226 WIP: Adding image removal check
  cip.go
  lib/dockerregistry/BUILD.bazel
  lib/dockerregistry/checks.go
  lib/dockerregistry/checks_test.go
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
  lib/dockerregistry/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/release, size/L

#233 Add ImageSizeCheck to the promoter
  cip.go
  lib/dockerregistry/checks.go
  lib/dockerregistry/checks_test.go
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
  lib/dockerregistry/types.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L
