Repository kubernetes-sigs/promo-tools, pull requests merged in 2020-08, with the labels that each got.

#249 remove PY2 usage from e2e tests
  test-e2e/cip-auditor/cip-auditor-e2e.go
  test-e2e/cip/e2e.go
Labels: approved, cncf-cla: yes, sig/release, size/XS

#250 Update build rules
  BUILD.bazel
  WORKSPACE
  test-e2e/cip-auditor/BUILD.bazel
  test-e2e/cip-auditor/fixture/basic/images/bar/images.yaml
  test-e2e/cip-auditor/fixture/basic/images/foo/images.yaml
  test-e2e/cip-auditor/fixture/fatManifest-subproject-different-prefix/images/foo/images.yaml
  test-e2e/cip-auditor/fixture/fatManifest/images/foo/images.yaml
  test-e2e/cip-auditor/tests.yaml
  test-e2e/cip/BUILD.bazel
  test-e2e/cip/fixture/recursive-thin/images/bar/images.yaml
  test-e2e/cip/fixture/recursive-thin/images/foo/images.yaml
  test-e2e/cip/fixture/sanity/promoter-manifest.yaml
  test-e2e/cip/tests.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#248 fixed issue where vulnerabilities were only getting logged when a fix…
  .golangci.yml
  cip.go
  lib/dockerregistry/checks.go
  lib/dockerregistry/checks_test.go
  lib/dockerregistry/types.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#252 disable some linters
  .golangci.yml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#256 add the adapter and files needed for the vulnerability dashboard
  Makefile
  cmd/promobot-files/BUILD.bazel
  dashboard/BUILD.bazel
  dashboard/adapter/BUILD.bazel
  dashboard/adapter/adapter.go
  dashboard/adapter/adapter_test.go
  dashboard/adapter/types.go
  dashboard/dashboard.go
  dashboard/dashboard.html
  dashboard/dashboard.js
  go.mod
  go.sum
  lib/dockerregistry/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XL

#257 add vulnerability dashboard documentation
  README.md
  dashboard/vulnerability_dashboard.md
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M
