Repository kubernetes-sigs/promo-tools, pull requests merged in 2020-10, with the labels that each got.

#263 Consolidate packages (part two)
  Makefile
  cmd/promobot-files/BUILD.bazel
  cmd/promobot-files/main.go
  cmd/promobot-generate-manifest/BUILD.bazel
  cmd/promobot-generate-manifest/main.go
  dashboard/BUILD.bazel
  dashboard/dashboard.go
  dashboard/vulnerability_dashboard.md
  go.mod
  pkg/go.mod
  pkg/promobot/BUILD.bazel
  pkg/promobot/hash.go
  pkg/promobot/hash_test.go
  pkg/promobot/promotefiles.go
  pkg/promobot/readmanifest_test.go
  pkg/promobot/testdata/files-manifest.yaml
  pkg/promobot/testdata/files/blue.png
  pkg/promobot/testdata/files/green.png
  pkg/promobot/testdata/files/red.png
  pkg/promobot/testdata/manifests/manyfiles/expected.yaml
  pkg/promobot/testdata/manifests/manyfiles/files/blue.yaml
  pkg/promobot/testdata/manifests/manyfiles/files/green.yaml
  pkg/promobot/testdata/manifests/manyfiles/files/red.yaml
  pkg/promobot/testdata/manifests/manyfiles/filestores.yaml
  pkg/promobot/testdata/manifests/onefiles/expected.yaml
  pkg/promobot/testdata/manifests/onefiles/files.yaml
  pkg/promobot/testdata/manifests/onefiles/filestores.yaml
  pkg/vulndash/adapter/BUILD.bazel
  pkg/vulndash/adapter/adapter.go
  pkg/vulndash/adapter/adapter_test.go
  pkg/vulndash/adapter/types.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#265 Update OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M

#267 github: add issue/PR templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/SECURITY.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, sig/release, size/L, tide/merge-method-squash, wg/k8s-infra

#264 Bazel updates
  .bazelversion
  BUILD.bazel
  Makefile
  WORKSPACE
  cmd/promobot-files/BUILD.bazel
  pkg/dockerregistry/BUILD.bazel
  test-e2e/cip-auditor/BUILD.bazel
  test-e2e/cip/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M, wg/k8s-infra

#272 cloudbuild.yaml: Use bazelbuild:latest-2.2.0
  cloudbuild.yaml
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, sig/release, size/XS, wg/k8s-infra

#273 Migrate non-essential promotion CLI tools to k/release
  BUILD.bazel
  Makefile
  cmd/cip-mm/BUILD.bazel
  cmd/cip-mm/README.md
  cmd/cip-mm/main.go
  cmd/promobot-files/BUILD.bazel
  cmd/promobot-files/README.md
  cmd/promobot-files/main.go
  cmd/promobot-generate-manifest/BUILD.bazel
  cmd/promobot-generate-manifest/README.md
  cmd/promobot-generate-manifest/main.go
  go.mod
  pkg/api/files/BUILD.bazel
  pkg/api/files/manifest.go
  pkg/api/files/manifest_test.go
  pkg/api/files/validation.go
  pkg/filepromoter/BUILD.bazel
  pkg/filepromoter/file.go
  pkg/filepromoter/filestore.go
  pkg/filepromoter/gcs.go
  pkg/filepromoter/interfaces.go
  pkg/filepromoter/manifest.go
  pkg/filepromoter/token.go
  pkg/go.mod
  pkg/promobot/BUILD.bazel
  pkg/promobot/hash.go
  pkg/promobot/hash_test.go
  pkg/promobot/promotefiles.go
  pkg/promobot/readmanifest_test.go
  pkg/promobot/testdata/files-manifest.yaml
  pkg/promobot/testdata/files/blue.png
  pkg/promobot/testdata/files/green.png
  pkg/promobot/testdata/files/red.png
  pkg/promobot/testdata/manifests/manyfiles/expected.yaml
  pkg/promobot/testdata/manifests/manyfiles/files/blue.yaml
  pkg/promobot/testdata/manifests/manyfiles/files/green.yaml
  pkg/promobot/testdata/manifests/manyfiles/files/red.yaml
  pkg/promobot/testdata/manifests/manyfiles/filestores.yaml
  pkg/promobot/testdata/manifests/onefiles/expected.yaml
  pkg/promobot/testdata/manifests/onefiles/files.yaml
  pkg/promobot/testdata/manifests/onefiles/filestores.yaml
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, sig/release, size/XXL, wg/k8s-infra

#275 update vulnerability documentation with the new link for the prow job
  dashboard/vulnerability_dashboard.md
Labels: approved, area/release-eng, cncf-cla: yes, kind/documentation, lgtm, release-note-none, sig/release, size/XS, wg/k8s-infra

#276 Migrate vulnerability dashboard to k/release
  Makefile
  README.md
  dashboard/BUILD.bazel
  dashboard/dashboard.go
  dashboard/dashboard.html
  dashboard/dashboard.js
  dashboard/vulnerability_dashboard.md
  pkg/go.mod
  pkg/vulndash/adapter/BUILD.bazel
  pkg/vulndash/adapter/adapter.go
  pkg/vulndash/adapter/adapter_test.go
  pkg/vulndash/adapter/types.go
Labels: approved, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, release-note, sig/release, size/XL, wg/k8s-infra
