Repository kubernetes-sigs/promo-tools, pull requests merged in 2020-02, with the labels that each got.

#172 fix perms for pull-cip-auditor-e2e test
  test-e2e/cip-auditor/cip-auditor-e2e.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#173 fix log formatting
  lib/dockerregistry/inventory.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#178 fix log formatting
  lib/dockerregistry/inventory.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#176 Files: add a command to generate manifests from a local path
  cmd/promobot-generate-manifest/BUILD.bazel
  cmd/promobot-generate-manifest/README.md
  cmd/promobot-generate-manifest/main.go
  go.mod
  go.sum
  pkg/cmd/BUILD.bazel
  pkg/cmd/hash.go
  pkg/cmd/hash_test.go
  pkg/cmd/testdata/files-manifest.yaml
  pkg/cmd/testdata/files/blue.png
  pkg/cmd/testdata/files/green.png
  pkg/cmd/testdata/files/red.png
  pkg/filepromoter/file.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#177 files: split manifests into filestores & files
  cmd/promobot-files/main.go
  go.mod
  go.sum
  pkg/cmd/promotefiles.go
  pkg/cmd/readmanifest_test.go
  pkg/cmd/testdata/manifests/manyfiles/expected.yaml
  pkg/cmd/testdata/manifests/manyfiles/files/blue.yaml
  pkg/cmd/testdata/manifests/manyfiles/files/green.yaml
  pkg/cmd/testdata/manifests/manyfiles/files/red.yaml
  pkg/cmd/testdata/manifests/manyfiles/filestores.yaml
  pkg/cmd/testdata/manifests/onefiles/expected.yaml
  pkg/cmd/testdata/manifests/onefiles/files.yaml
  pkg/cmd/testdata/manifests/onefiles/filestores.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#174 add bartsmykla to OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#181 Makefile/bazel fixes
  Makefile
  WORKSPACE
  cmd/promobot-generate-manifest/BUILD.bazel
  go.mod
  go.sum
  pkg/cmd/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XXL

#182 Makefile: make "make" run the build before testing
  Makefile
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS
