Repository kubernetes-sigs/promo-tools, pull requests merged in 2020-07, with the labels that each got.

#241 Disable new golangci-lint linters
  .golangci.yml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#238 moved WaitGroup drain to after request results processed
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#240 Add promobot-files to the staging image build
  Makefile
  cmd/promobot-files/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M

#243 remove dead code
  lib/dockerregistry/inventory.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M

#242 MkRequestsCapturer: do not manually decrement semaphore
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#236 WIP: add a vulnerability check for the promoter
  cip.go
  go.mod
  go.sum
  lib/dockerregistry/BUILD.bazel
  lib/dockerregistry/checks.go
  lib/dockerregistry/checks_test.go
  lib/dockerregistry/inventory.go
  lib/dockerregistry/inventory_test.go
  lib/dockerregistry/types.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#244 Allow file manifest export to filter by prefix
  cmd/promobot-generate-manifest/main.go
  pkg/cmd/hash.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#245 modify the vulnerability to check against fixable vulnerabilities
  lib/dockerregistry/checks.go
  lib/dockerregistry/checks_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M

#247 remove dead code
  lib/dockerregistry/inventory.go
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#246 update the checks interface readme to include the vulnerability check
  checks_interface.md
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M
