Repository kubernetes-sigs/promo-tools, pull requests merged in 2021-10, with the labels that each got.

#437 filepromoter: Prefer `Confirm` instead of `DryRun`
  VERSION
  cloudbuild.yaml
  cmd/kpromo/README.md
  cmd/kpromo/cmd/run/files.go
  dependencies.yaml
  filepromoter/filestore.go
  filepromoter/filestore_test.go
  filepromoter/manifest.go
  promobot/promotefiles.go
  workspace_status.sh
Labels: cncf-cla: yes, size/M, approved, lgtm, kind/cleanup, release-note, sig/release, kind/deprecation, area/release-eng, area/artifacts

#440 Inject build information during tool installation
  Dockerfile
  Makefile
  cmd/kpromo/cmd/cip/version.go
  cmd/kpromo/cmd/root.go
  cmd/kpromo/cmd/version/version.go
  go_with_version.sh
  hack/cip-image.sh
  workspace_status.sh
Labels: kind/feature, cncf-cla: yes, size/L, approved, lgtm, release-note, sig/release, area/release-eng, area/artifacts

#442 Dockerfile: Restore Docker configuration to production container
  Dockerfile
  cloudbuild.yaml
  dependencies.yaml
  workspace_status.sh
Labels: cncf-cla: yes, approved, lgtm, priority/critical-urgent, size/XS, release-note, sig/release, kind/regression, area/release-eng, area/artifacts

#441 Move `gh2gcs` functionality to `kpromo gh`
  Makefile
  VERSION
  cloudbuild.yaml
  cmd/gh2gcs/README.md
  cmd/gh2gcs/main.go
  cmd/kpromo/cmd/gh/README.md
  cmd/kpromo/cmd/gh/gh.go
  cmd/kpromo/cmd/root.go
  dependencies.yaml
  gh2gcs/gh2gcs.go
  hack/verify-build.sh
  workspace_status.sh
Labels: cncf-cla: yes, size/L, approved, lgtm, kind/cleanup, release-note, sig/release, kind/deprecation, area/release-eng, area/artifacts

#443 Dockerfile: Copy Docker config file to `$HOME/.docker/config.json`
  Dockerfile
  cloudbuild.yaml
  dependencies.yaml
  workspace_status.sh
Labels: kind/bug, cncf-cla: yes, approved, lgtm, priority/critical-urgent, size/S, release-note, sig/release, area/release-eng, area/artifacts
