Repository kubernetes-sigs/promo-tools, pull requests merged in 2021-11, with the labels that each got.

#457 Remove references to vulndash
  README.md
Labels: cncf-cla: yes, release-note-none, approved, lgtm, kind/cleanup, size/XS, sig/release, area/release-eng, area/artifacts

#458 kpromo: Add `krel promote-images` functionality
  VERSION
  cloudbuild.yaml
  cmd/kpromo/cmd/pr/pr.go
  cmd/kpromo/cmd/root.go
  dependencies.yaml
  image/image.go
  image/image_test.go
  workspace_status.sh
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/XL, release-note, sig/release, area/release-eng, area/artifacts

#460 kpromo(pr): Minor cleanups
  cmd/kpromo/cmd/pr/pr.go
  go.mod
  go.sum
Labels: cncf-cla: yes, size/L, approved, lgtm, kind/cleanup, release-note, sig/release, area/dependency, area/release-eng, area/artifacts

#461 Update to github.com/google/go-containerregistry@main
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm, kind/cleanup, release-note, sig/release, area/dependency, area/release-eng, area/artifacts

#462 Docs reshuffle
  README.md
  docs/checks.md
  docs/development.md
  docs/file-promotion.md
  docs/github-promotion.md
  docs/image-promotion.md
  docs/promotion-pull-requests.md
Labels: cncf-cla: yes, kind/documentation, release-note-none, approved, lgtm, size/XL, kind/cleanup, sig/release, area/release-eng, area/artifacts

#464 kpromo: add missing spaces after project and reviewers args in PR body
  cmd/kpromo/cmd/pr/pr.go
Labels: kind/bug, cncf-cla: yes, approved, lgtm, size/XS, release-note, sig/release, area/release-eng, area/artifacts

#465 kpromo: add quotes around reviewers in command print
  cmd/kpromo/cmd/pr/pr.go
Labels: cncf-cla: yes, approved, lgtm, size/XS, release-note, sig/release, area/release-eng, area/artifacts
