Repository kubernetes-sigs/promo-tools, pull requests merged in 2021-08, with the labels that each got.

#386 Fixed comment within reqcounter
  legacy/reqcounter/reqcounter.go
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, release-note, sig/release, size/XS, wg/k8s-infra

#389 Watch OS signals when providing --verbose flag
  legacy/cli/audit.go
  legacy/signals/signals.go
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/feature, lgtm, release-note, sig/release, size/M, wg/k8s-infra

#388 Create script to run auditor locally
  hack/local-audit.sh
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/feature, lgtm, release-note, sig/release, size/M, wg/k8s-infra

#385 abort promoter if we detect an attempt to perform a tag move in the destination (in production)
  legacy/dockerregistry/inventory.go
  legacy/dockerregistry/inventory_test.go
Labels: kind/bug, cncf-cla: yes, wg/k8s-infra, size/L, approved, lgtm, kind/cleanup, release-note, sig/release, area/release-eng, area/artifacts

#391 Add unit tests to signals package
  legacy/signals/signals.go
  legacy/signals/signals_test.go
Labels: cncf-cla: yes, wg/k8s-infra, size/L, approved, lgtm, kind/cleanup, release-note, sig/release, area/release-eng, area/artifacts

#394 Update verify tooling and fixup lint warnings
  .golangci.yml
  dependencies.yaml
  hack/verify-boilerplate.sh
  hack/verify-dependencies.sh
  hack/verify-golangci-lint.sh
  legacy/audit/auditor.go
  legacy/audit/auditor_test.go
  legacy/cli/run.go
  legacy/dockerregistry/checks.go
  legacy/dockerregistry/checks_test.go
  legacy/dockerregistry/inventory.go
  legacy/dockerregistry/inventory_test.go
  legacy/signals/signals.go
  legacy/stream/http.go
  test-e2e/cip-auditor/cip-auditor-e2e.go
  test-e2e/cip/e2e.go
Labels: cncf-cla: yes, wg/k8s-infra, release-note-none, approved, lgtm, size/XL, kind/cleanup, sig/release, area/release-eng, area/artifacts

#349 dependency: Replace `klog` with `logrus`
  go.mod
  go.sum
  test-e2e/cip-auditor/cip-auditor-e2e.go
  test-e2e/cip/e2e.go
Labels: cncf-cla: yes, size/M, wg/k8s-infra, release-note-none, approved, lgtm, kind/cleanup, sig/release, area/release-eng, area/artifacts

#396 go_with_version.sh: Shellcheck and drop `return` statement
  go_with_version.sh
Labels: cncf-cla: yes, wg/k8s-infra, release-note-none, approved, lgtm, kind/cleanup, size/XS, sig/release, area/release-eng, area/artifacts

#397 Dockerfile: Use an explicit go version (go1.16.7) for image building
  Dockerfile
  dependencies.yaml
Labels: cncf-cla: yes, wg/k8s-infra, approved, lgtm, kind/cleanup, size/S, release-note, sig/release, area/dependency, area/release-eng, area/artifacts

#403 test-e2e/cip: Remove checkEqual() function
  go.mod
  test-e2e/cip/e2e.go
Labels: cncf-cla: yes, size/M, wg/k8s-infra, release-note-none, approved, lgtm, kind/cleanup, sig/release, area/release-eng, area/artifacts

#407 Migrate kpromo/cip-mm tools/packages into repo
  api/files/manifest.go
  api/files/manifest_test.go
  api/files/validation.go
  cmd/cip-mm/README.md
  cmd/cip-mm/main.go
  cmd/kpromo/Dockerfile
  cmd/kpromo/Makefile
  cmd/kpromo/README.md
  cmd/kpromo/cloudbuild.yaml
  cmd/kpromo/cmd/manifest/files.go
  cmd/kpromo/cmd/manifest/manifest.go
  cmd/kpromo/cmd/root.go
  cmd/kpromo/cmd/run/files.go
  cmd/kpromo/cmd/run/run.go
  cmd/kpromo/main.go
  cmd/kpromo/variants.yaml
  filepromoter/file.go
  filepromoter/filestore.go
  filepromoter/gcs.go
  filepromoter/interfaces.go
  filepromoter/manifest.go
  filepromoter/token.go
  go.mod
  go.sum
  promobot/hash.go
  promobot/hash_test.go
  promobot/promotefiles.go
  promobot/readmanifest_test.go
  promobot/testdata/files-manifest.yaml
  promobot/testdata/files/blue.png
  promobot/testdata/files/green.png
  promobot/testdata/files/red.png
  promobot/testdata/manifests/manyfiles/expected.yaml
  promobot/testdata/manifests/manyfiles/files/blue.yaml
  promobot/testdata/manifests/manyfiles/files/green.yaml
  promobot/testdata/manifests/manyfiles/files/red.yaml
  promobot/testdata/manifests/manyfiles/filestores.yaml
  promobot/testdata/manifests/onefiles/expected.yaml
  promobot/testdata/manifests/onefiles/files.yaml
  promobot/testdata/manifests/onefiles/filestores.yaml
Labels: kind/feature, cncf-cla: yes, wg/k8s-infra, approved, lgtm, kind/cleanup, size/XXL, release-note, sig/release, area/release-eng, area/artifacts
