Repository kubernetes-sigs/promo-tools, pull requests merged in 2021-06, with the labels that each got.

#303 Use `sigs.k8s.io/release-utils/command`
  legacy/gcloud/BUILD.bazel
  legacy/gcloud/token.go
  test-e2e/cip-auditor/BUILD.bazel
  test-e2e/cip-auditor/cip-auditor-e2e.go
  test-e2e/cip/BUILD.bazel
  test-e2e/cip/e2e.go
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, release-note, sig/release, size/L, wg/k8s-infra

#305 Generate Docker archives for golden images
  .gitignore
  Makefile
  hack/verify-archives.sh
  test-e2e/cip/golden-archives/bar/1.0.tar
  test-e2e/cip/golden-archives/foo/1.0-linux_amd64.tar
  test-e2e/cip/golden-archives/foo/1.0-linux_s390x.tar
  test-e2e/cip/golden-archives/foo/NOTAG-0.tar
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note, sig/release, size/M, wg/k8s-infra

#307 Added staging names to golden-archives
  hack/verify-archives.sh
  test-e2e/cip/golden-archives/bar/1.0.tar
  test-e2e/cip/golden-archives/foo/1.0-linux_amd64.tar
  test-e2e/cip/golden-archives/foo/1.0-linux_s390x.tar
  test-e2e/cip/golden-archives/foo/NOTAG-0.tar
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note, sig/release, size/XS, wg/k8s-infra

#301 fix cip-postsubmit-push-to-staging error on tagged commits
  workspace_status.sh
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, lgtm, release-note-none, sig/release, size/M, wg/k8s-infra

#311 workspace_status.sh: Simplify git/image tagging logic
  BUILD.bazel
  cloudbuild.yaml
  test-e2e/cip-auditor/BUILD.bazel
  workspace_status.sh
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, sig/release, size/M, wg/k8s-infra

#306 Integrate archive loading into e2e tests
  test-e2e/cip/e2e.go
  test-e2e/cip/fixture/recursive-thin/images/bar/images.yaml
  test-e2e/cip/fixture/recursive-thin/images/foo/images.yaml
  test-e2e/cip/fixture/sanity/promoter-manifest.yaml
  test-e2e/cip/push-golden.sh
  test-e2e/cip/tests.yaml
  workspace_status.sh
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/cleanup, kind/deprecation, lgtm, ok-to-test, release-note, sig/release, size/L, wg/k8s-infra

#308 Remove all Bazel invocations from test-e2e-cip
  Makefile
  go_with_version.sh
  test-e2e/cip/e2e.go
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/cleanup, kind/deprecation, lgtm, release-note, sig/release, size/M, wg/k8s-infra

#313 gcb: Temporarily disable incorrectly failing `images` check
  cloudbuild.yaml
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, sig/release, size/S, wg/k8s-infra

#314 Adapt push-golden.sh for audits
  test-e2e/cip/e2e.go
  test-e2e/cip/push-golden.sh
  test-e2e/push-golden.sh
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/cleanup, kind/deprecation, lgtm, release-note, sig/release, size/L, wg/k8s-infra

#315 Integrate archive loading into test-e2e-cip-auditor
  test-e2e/cip-auditor/cip-auditor-e2e.go
  test-e2e/cip-auditor/fixture/basic/images/bar/images.yaml
  test-e2e/cip-auditor/fixture/basic/images/foo/images.yaml
  test-e2e/cip-auditor/fixture/fatManifest-subproject-different-prefix/images/foo/images.yaml
  test-e2e/cip-auditor/fixture/fatManifest/images/foo/images.yaml
  test-e2e/cip-auditor/tests.yaml
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/cleanup, kind/deprecation, lgtm, release-note, sig/release, size/L, wg/k8s-infra

#316 Remove Bazel from building and executing auditor within Makefile
  Makefile
  test-e2e/cip-auditor/cip-auditor-e2e.go
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/cleanup, kind/deprecation, lgtm, release-note, sig/release, size/M, wg/k8s-infra

#317 Migrate golden-image artifacts into test-e2e/golden-images
  hack/verify-archives.sh
  test-e2e/cip-auditor/cip-auditor-e2e.go
  test-e2e/cip/e2e.go
  test-e2e/golden-images/archives/bar/1.0.tar
  test-e2e/golden-images/archives/foo/1.0-linux_amd64.tar
  test-e2e/golden-images/archives/foo/1.0-linux_s390x.tar
  test-e2e/golden-images/archives/foo/NOTAG-0.tar
  test-e2e/golden-images/content/bar/1.0
  test-e2e/golden-images/content/foo/1.0-linux_amd64
  test-e2e/golden-images/content/foo/1.0-linux_s390x
  test-e2e/golden-images/content/foo/NOTAG-0
  test-e2e/golden-images/push-golden.sh
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, release-note, sig/release, size/S, wg/k8s-infra

#319 Add more detailed logging statement in auditor
  test-e2e/cip-auditor/cip-auditor-e2e.go
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, release-note, sig/release, size/XS, wg/k8s-infra

#318 Create archive bundle for auditor
  Dockerfile
  Makefile
  test-e2e/cip-auditor/push-cip-auditor-test.sh
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/cleanup, kind/deprecation, lgtm, release-note, sig/release, size/M, wg/k8s-infra

#320 Remove unused make target: image-load-cip-auditor-e2e
  Makefile
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/cleanup, kind/deprecation, lgtm, release-note, sig/release, size/XS, wg/k8s-infra

#324 Building cip with go CLI
  Makefile
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/cleanup, kind/deprecation, lgtm, release-note, sig/release, size/S, wg/k8s-infra
