Repository kubernetes-sigs/promo-tools, pull requests merged in 2021-09, with the labels that each got.

#408 kpromo: Initial merge of image building files
  Dockerfile-kpromo
  Makefile-kpromo
  cloudbuild.yaml
  cmd/kpromo/cloudbuild.yaml
  hack/init-buildx.sh
Labels: cncf-cla: yes, wg/k8s-infra, size/L, approved, lgtm, kind/cleanup, release-note, sig/release, area/release-eng, area/artifacts

#409 `kpromo`: Support multiple-project file promotions
  Dockerfile
  Makefile-kpromo
  cloudbuild.yaml
  cmd/kpromo/cmd/run/files.go
  dependencies.yaml
  filepromoter/filestore.go
  go.mod
  promobot/promotefiles.go
  promobot/readmanifest_test.go
  promobot/testdata/expected/manyfiles.yaml
  promobot/testdata/expected/manyprojects.yaml
  promobot/testdata/expected/onefile.yaml
  promobot/testdata/manifests/manyfiles/expected.yaml
  promobot/testdata/manifests/manyfiles/filepromoter-manifest.yaml
  promobot/testdata/manifests/manyprojects/filestores/project1/filepromoter-manifest.yaml
  promobot/testdata/manifests/manyprojects/filestores/project2/filepromoter-manifest.yaml
  promobot/testdata/manifests/manyprojects/manifests/project1/blue.yaml
  promobot/testdata/manifests/manyprojects/manifests/project1/green.yaml
  promobot/testdata/manifests/manyprojects/manifests/project1/red.yaml
  promobot/testdata/manifests/manyprojects/manifests/project2/blue.yaml
  promobot/testdata/manifests/manyprojects/manifests/project2/green.yaml
  promobot/testdata/manifests/manyprojects/manifests/project2/red.yaml
  promobot/testdata/manifests/onefile/filepromoter-manifest.yaml
  promobot/testdata/manifests/onefile/files.yaml
  promobot/testdata/manifests/onefiles/expected.yaml
Labels: kind/feature, cncf-cla: yes, wg/k8s-infra, size/L, approved, lgtm, kind/cleanup, release-note, sig/release, area/dependency, area/release-eng, area/artifacts

#412 kpromo: Improve service account usage/retrieval
  Makefile-kpromo
  cloudbuild.yaml
  cmd/kpromo/README.md
  cmd/kpromo/cmd/run/files.go
  dependencies.yaml
  filepromoter/filestore.go
  filepromoter/manifest.go
  promobot/promotefiles.go
Labels: kind/bug, cncf-cla: yes, size/M, wg/k8s-infra, approved, lgtm, release-note, sig/release, area/release-eng, area/artifacts

#415 kpromo: Use gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  Dockerfile-kpromo
  Makefile-kpromo
  cloudbuild.yaml
  cmd/kpromo/variants.yaml
  dependencies.yaml
Labels: cncf-cla: yes, size/M, wg/k8s-infra, approved, lgtm, release-note, sig/release, area/release-eng, area/artifacts

#416 Lintlintlint
  .golangci.yml
  dependencies.yaml
  hack/verify-golangci-lint.sh
  legacy/audit/auditor.go
  legacy/audit/auditor_test.go
  legacy/audit/types.go
  legacy/cli/run.go
  legacy/dockerregistry/checks.go
  legacy/dockerregistry/grow_manifest.go
  legacy/dockerregistry/inventory.go
  legacy/dockerregistry/inventory_test.go
  legacy/dockerregistry/types.go
  legacy/report/gcp.go
Labels: cncf-cla: yes, wg/k8s-infra, size/L, release-note-none, approved, lgtm, kind/cleanup, sig/release, area/release-eng, area/artifacts

#417 filepromoter: Warn on (but don't block) unauthenticated operations
  Makefile-kpromo
  cloudbuild.yaml
  dependencies.yaml
  filepromoter/filestore.go
Labels: kind/bug, cncf-cla: yes, wg/k8s-infra, approved, lgtm, size/S, release-note, sig/release, area/release-eng, area/artifacts

#420 filepromoter: Allow authenticated clients in non-production runs
  Makefile-kpromo
  cloudbuild.yaml
  cmd/kpromo/README.md
  cmd/kpromo/cmd/run/files.go
  dependencies.yaml
  filepromoter/filestore.go
  filepromoter/filestore_test.go
  filepromoter/manifest.go
  promobot/promotefiles.go
Labels: cncf-cla: yes, wg/k8s-infra, size/L, approved, lgtm, release-note, sig/release, kind/regression, area/release-eng, area/artifacts

#422 filepromoter: Build unauthenticated client for source filestores
  Makefile-kpromo
  cloudbuild.yaml
  dependencies.yaml
  filepromoter/filestore.go
  filepromoter/filestore_test.go
Labels: kind/bug, cncf-cla: yes, size/M, wg/k8s-infra, approved, lgtm, release-note, sig/release, area/release-eng, area/artifacts

#421 OWNERS cleanup
  OWNERS
  OWNERS_ALIASES
  SECURITY_CONTACTS
Labels: cncf-cla: yes, size/M, wg/k8s-infra, release-note-none, approved, lgtm, kind/cleanup, sig/release, area/release-eng, area/artifacts

#423 Migrate `gh2gcs` tool/packages into repo
  cmd/gh2gcs/README.md
  cmd/gh2gcs/cmd/root.go
  cmd/gh2gcs/main.go
  gh2gcs/gh2gcs.go
  go.mod
  go.sum
Labels: kind/feature, cncf-cla: yes, wg/k8s-infra, size/L, approved, lgtm, release-note, sig/release, area/release-eng, area/artifacts

#285 cmd/cip: Default to non-production runs with `--confirm`
  cmd/cip/cmd/root.go
  cmd/cip/cmd/run.go
  legacy/cli/root.go
  legacy/cli/run.go
  legacy/dockerregistry/inventory.go
  legacy/dockerregistry/types.go
  test-e2e/cip-auditor/cip-auditor-e2e.go
  test-e2e/cip/e2e.go
Labels: kind/bug, cncf-cla: yes, wg/k8s-infra, size/L, approved, lgtm, priority/critical-urgent, release-note, sig/release, kind/regression, area/release-eng, area/artifacts

#425 go.mod: Init v3 module
  api/files/manifest_test.go
  cmd/cip-mm/main.go
  cmd/cip/cmd/audit.go
  cmd/cip/cmd/root.go
  cmd/cip/cmd/run.go
  cmd/cip/cmd/version.go
  cmd/cip/main.go
  cmd/gh2gcs/cmd/root.go
  cmd/gh2gcs/main.go
  cmd/kpromo/cmd/manifest/files.go
  cmd/kpromo/cmd/root.go
  cmd/kpromo/cmd/run/files.go
  cmd/kpromo/main.go
  filepromoter/file.go
  filepromoter/filepromoterfakes/fake_sync_file_op.go
  filepromoter/filepromoterfakes/fake_sync_filestore.go
  filepromoter/filestore.go
  filepromoter/filestore_test.go
  filepromoter/gcs.go
  filepromoter/manifest.go
  filepromoter/token.go
  go.mod
  legacy/audit/auditor.go
  legacy/audit/auditor_test.go
  legacy/audit/types.go
  legacy/cli/audit.go
  legacy/cli/root.go
  legacy/cli/run.go
  legacy/cli/version.go
  legacy/dockerregistry/checks.go
  legacy/dockerregistry/checks_test.go
  legacy/dockerregistry/grow_manifest_test.go
  legacy/dockerregistry/inventory.go
  legacy/dockerregistry/inventory_test.go
  legacy/dockerregistry/set.go
  legacy/dockerregistry/types.go
  legacy/remotemanifest/fake.go
  legacy/remotemanifest/git.go
  legacy/remotemanifest/types.go
  legacy/reqcounter/reqcounter.go
  legacy/reqcounter/reqcounter_test.go
  legacy/signals/signals_test.go
  promobot/hash.go
  promobot/hash_test.go
  promobot/promotefiles.go
  promobot/readmanifest_test.go
  test-e2e/cip-auditor/cip-auditor-e2e.go
  test-e2e/cip/e2e.go
Labels: kind/feature, cncf-cla: yes, wg/k8s-infra, size/L, approved, lgtm, kind/api-change, release-note, sig/release, area/release-eng, area/artifacts

#426 v3.2.0: Release commit
  Makefile-kpromo
  VERSION
  cloudbuild.yaml
  dependencies.yaml
Labels: kind/feature, cncf-cla: yes, wg/k8s-infra, release-note-none, approved, lgtm, tide/merge-method-squash, size/S, sig/release, area/release-eng, area/artifacts

#427 cloudbuild.yaml: Re-enable image checks for CIP + auditor
  cloudbuild.yaml
Labels: cncf-cla: yes, wg/k8s-infra, approved, lgtm, kind/cleanup, size/S, release-note, sig/release, area/release-eng, area/artifacts

#428 Module rename: sigs.k8s.io/k8s-container-image-promoter --> sigs.k8s.io/promo-tools
  Dockerfile-kpromo
  README.md
  api/files/manifest_test.go
  checks_interface.md
  cmd/cip-mm/main.go
  cmd/cip/cmd/audit.go
  cmd/cip/cmd/root.go
  cmd/cip/cmd/run.go
  cmd/cip/cmd/version.go
  cmd/cip/main.go
  cmd/gh2gcs/cmd/root.go
  cmd/gh2gcs/main.go
  cmd/kpromo/cmd/manifest/files.go
  cmd/kpromo/cmd/root.go
  cmd/kpromo/cmd/run/files.go
  cmd/kpromo/main.go
  filepromoter/file.go
  filepromoter/filepromoterfakes/fake_sync_file_op.go
  filepromoter/filepromoterfakes/fake_sync_filestore.go
  filepromoter/filestore.go
  filepromoter/filestore_test.go
  filepromoter/gcs.go
  filepromoter/manifest.go
  filepromoter/token.go
  go.mod
  go_with_version.sh
  hack/test-go.sh
  legacy/audit/auditor.go
  legacy/audit/auditor_test.go
  legacy/audit/types.go
  legacy/cli/audit.go
  legacy/cli/root.go
  legacy/cli/run.go
  legacy/cli/version.go
  legacy/dockerregistry/checks.go
  legacy/dockerregistry/checks_test.go
  legacy/dockerregistry/grow_manifest_test.go
  legacy/dockerregistry/inventory.go
  legacy/dockerregistry/inventory_test.go
  legacy/dockerregistry/set.go
  legacy/dockerregistry/types.go
  legacy/remotemanifest/fake.go
  legacy/remotemanifest/git.go
  legacy/remotemanifest/types.go
  legacy/reqcounter/reqcounter.go
  legacy/reqcounter/reqcounter_test.go
  legacy/signals/signals_test.go
  promobot/hash.go
  promobot/hash_test.go
  promobot/promotefiles.go
  promobot/readmanifest_test.go
  test-e2e/cip-auditor/cip-auditor-e2e.go
  test-e2e/cip/e2e.go
Labels: cncf-cla: yes, wg/k8s-infra, size/L, approved, lgtm, release-note, sig/release, kind/deprecation, area/release-eng, area/artifacts

#432 drop wg/k8s-infra label
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature.md
  OWNERS
Labels: cncf-cla: yes, wg/k8s-infra, release-note-none, approved, lgtm, kind/cleanup, size/XS, sig/release, area/release-eng, area/artifacts

#433 docs: mv wg-k8s-infra sig-k8s-infra
  checks_interface.md
Labels: cncf-cla: yes, kind/documentation, release-note-none, approved, lgtm, kind/cleanup, size/XS, sig/release, area/release-eng, area/artifacts

#434 Move container image promotion commands into `kpromo`
  Dockerfile
  Dockerfile-kpromo
  Makefile
  Makefile-kpromo
  VERSION
  cloudbuild.yaml
  cmd/cip/cmd/root.go
  cmd/cip/main.go
  cmd/kpromo/cmd/cip/audit.go
  cmd/kpromo/cmd/cip/cip.go
  cmd/kpromo/cmd/cip/version.go
  cmd/kpromo/cmd/root.go
  dependencies.yaml
  hack/cip-image.sh
  test-e2e/cip-auditor/cip-auditor-e2e.go
  test-e2e/cip-auditor/tests.yaml
  test-e2e/cip/e2e.go
  test-e2e/golden-images/push-golden.sh
  workspace_status.sh
Labels: cncf-cla: yes, size/L, approved, lgtm, kind/cleanup, release-note, sig/release, area/release-eng, area/artifacts
