Repository kubernetes-sigs/promo-tools, pull requests merged in 2021-12, with the labels that each got.

#399 Find how many HTTP requests it takes to validate a given sub-project
  cmd/kpromo/cmd/pr/pr.go
  hack/count-requests.go
Labels: kind/feature, cncf-cla: yes, size/L, approved, lgtm, release-note, sig/release, area/release-eng, area/artifacts, sig/k8s-infra

#393 Created script to test GCR throttling
  cmd/count-requests/main.go
  cmd/verify-gcr-quota/main.go
Labels: kind/feature, cncf-cla: yes, size/L, approved, lgtm, release-note, sig/release, area/release-eng, area/artifacts, sig/k8s-infra

#419 Add kpromo manifest validate subcommand
  cmd/kpromo/cmd/manifest/validate.go
Labels: kind/feature, cncf-cla: yes, size/L, approved, lgtm, release-note, sig/release, area/release-eng, area/artifacts, sig/k8s-infra

#351 `kpromo cip`: Initial parent image verification work
  VERSION
  cloudbuild.yaml
  cmd/kpromo/cmd/cip/cip.go
  dependencies.yaml
  docs/promotion-pull-requests.md
  legacy/cli/run.go
  legacy/dockerregistry/inventory.go
  legacy/dockerregistry/types.go
  workspace_status.sh
Labels: cncf-cla: yes, size/L, approved, lgtm, release-note, sig/release, area/release-eng, area/artifacts, sig/k8s-infra

#468 legacy: Remove unused code paths
  legacy/cli/root.go
  legacy/dockerregistry/checks.go
  legacy/dockerregistry/inventory.go
  legacy/dockerregistry/inventory_test.go
  legacy/dockerregistry/set.go
  legacy/dockerregistry/types.go
  legacy/stream/types.go
Labels: cncf-cla: yes, size/L, approved, lgtm, kind/api-change, kind/cleanup, release-note, sig/release, kind/deprecation, area/release-eng, area/artifacts

#472 Add "install" subcommand to go_with_version.sh
  go_with_version.sh
Labels: kind/bug, cncf-cla: yes, release-note-none, approved, lgtm, size/XS, sig/release, area/release-eng, area/artifacts

#474 Minor issues grabbing the latest kpromo tool
  docs/promotion-pull-requests.md
Labels: cncf-cla: yes, kind/documentation, release-note-none, approved, lgtm, kind/cleanup, size/XS, sig/release, area/release-eng, area/artifacts

#477 Improve logging messages for inventory operations (1/n)
  legacy/dockerregistry/inventory.go
Labels: cncf-cla: yes, release-note-none, approved, lgtm, kind/cleanup, size/S, sig/release, area/release-eng, area/artifacts
