Repository kubernetes-sigs/promo-tools, pull requests merged in 2021-07, with the labels that each got.

#323 Replace Bazel image creation with Docker
  Dockerfile
  Makefile
  cloudbuild.yaml
  go_with_version.sh
  hack/push-cip.sh
  test-e2e/cip-auditor/push-cip-auditor-test.sh
  test-e2e/golden-images/push-golden.sh
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/cleanup, kind/deprecation, lgtm, release-note, sig/release, size/L, wg/k8s-infra

#331 Modify push-cip.sh to handle builds and pushes separately
  Makefile
  hack/cip-image.sh
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, release-note, sig/release, size/M, wg/k8s-infra

#330 docs: Update references to k/k8s.io default branch
  README.md
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note-none, sig/release, size/XS, wg/k8s-infra

#327 support serial unit test execution
  hack/test-go.sh
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/feature, lgtm, release-note-none, sig/release, size/S, wg/k8s-infra

#333 Remove all Bazel artifacts
  .bazelrc
  .bazelversion
  .gitignore
  BUILD.bazel
  README.md
  WORKSPACE
  cmd/cip/BUILD.bazel
  cmd/cip/cmd/BUILD.bazel
  hack/verify-archives.sh
  internal/version/BUILD.bazel
  legacy/audit/BUILD.bazel
  legacy/cli/BUILD.bazel
  legacy/container/BUILD.bazel
  legacy/dockerregistry/BUILD.bazel
  legacy/dockerregistry/grow_manifest_test.go
  legacy/dockerregistry/inventory_test.go
  legacy/gcloud/BUILD.bazel
  legacy/json/BUILD.bazel
  legacy/logclient/BUILD.bazel
  legacy/remotemanifest/BUILD.bazel
  legacy/report/BUILD.bazel
  legacy/stream/BUILD.bazel
  repos.bzl
  test-e2e/README.md
  test-e2e/cip-auditor/BUILD.bazel
  test-e2e/cip-auditor/cip-auditor-e2e.go
  test-e2e/cip/BUILD.bazel
  test-e2e/golden-images/push-golden.sh
  tools/go_sdk/BUILD
  tools/go_sdk/WORKSPACE
  tools/go_sdk/sdk.bzl
  workspace_status.sh
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/cleanup, kind/deprecation, lgtm, release-note, sig/release, size/XXL, wg/k8s-infra

#336 Remove bazel configurations from repo
  .bazelrc
  .bazelversion
  .gitignore
  BUILD.bazel
  Makefile
  README.md
  WORKSPACE
  cmd/cip/BUILD.bazel
  cmd/cip/cmd/BUILD.bazel
  cmd/cip/cmd/root.go
  hack/verify-archives.sh
  internal/version/BUILD.bazel
  legacy/audit/BUILD.bazel
  legacy/cli/BUILD.bazel
  legacy/cli/root.go
  legacy/container/BUILD.bazel
  legacy/dockerregistry/BUILD.bazel
  legacy/gcloud/BUILD.bazel
  legacy/json/BUILD.bazel
  legacy/logclient/BUILD.bazel
  legacy/remotemanifest/BUILD.bazel
  legacy/report/BUILD.bazel
  legacy/stream/BUILD.bazel
  repos.bzl
  test-e2e/README.md
  test-e2e/cip-auditor/BUILD.bazel
  test-e2e/cip-auditor/cip-auditor-e2e.go
  test-e2e/cip/BUILD.bazel
  test-e2e/golden-images/push-golden.sh
  tools/go_sdk/BUILD
  tools/go_sdk/WORKSPACE
  tools/go_sdk/sdk.bzl
  workspace_status.sh
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, priority/critical-urgent, release-note-none, sig/release, size/XXL, wg/k8s-infra

#337 Upgrade go dependencies
  go.mod
  go.sum
Labels: approved, area/artifacts, area/dependency, area/release-eng, cncf-cla: yes, kind/cleanup, kind/feature, lgtm, release-note, sig/release, size/L, wg/k8s-infra

#338 .github: Add dependabot config
  .github/dependabot.yml
Labels: approved, area/artifacts, area/dependency, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, sig/release, size/S, wg/k8s-infra

#342 Auditor Hotfix
  test-e2e/cip-auditor/cip-auditor-e2e.go
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/failing-test, lgtm, release-note, sig/release, size/XS, wg/k8s-infra

#346 Remove --version flag from cip command.
  cmd/cip/cmd/root.go
  legacy/cli/root.go
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/api-change, kind/bug, kind/cleanup, lgtm, release-note, sig/release, size/XS, wg/k8s-infra

#354 Added --verbose flag for extra logging info
  cmd/cip/cmd/audit.go
  legacy/audit/auditor.go
  legacy/audit/types.go
  legacy/cli/audit.go
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/api-change, kind/feature, lgtm, release-note, sig/release, size/S, wg/k8s-infra

#355 Fixing malformed auditor logging message
  legacy/cli/audit.go
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, release-note, sig/release, size/XS, wg/k8s-infra

#359 Introduce a request counter to the auditor
  legacy/cli/audit.go
  legacy/reqcounter/reqcounter.go
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/feature, lgtm, release-note, sig/release, size/M, wg/k8s-infra

#357 Fix unit tests
  legacy/audit/auditor_test.go
  legacy/dockerregistry/checks_test.go
  legacy/dockerregistry/grow_manifest_test.go
  legacy/dockerregistry/inventory_test.go
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/bug, kind/regression, lgtm, release-note-none, sig/release, size/XL, wg/k8s-infra

#362 gitignore: add tmp/
  .gitignore
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, sig/release, size/XS, wg/k8s-infra

#363 Log request counter every 10min
  legacy/dockerregistry/inventory.go
  legacy/reqcounter/reqcounter.go
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/feature, lgtm, release-note, sig/release, size/M, wg/k8s-infra

#364 Support multiple request counters
  legacy/reqcounter/reqcounter.go
  legacy/reqcounter/reqcounter_test.go
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/feature, lgtm, release-note, sig/release, size/L, wg/k8s-infra

#367 Added --verbose flag to auditor builds
  Dockerfile
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/feature, lgtm, release-note, sig/release, size/XS, wg/k8s-infra

#371 Created a timewrapper package to mock time functions
  legacy/reqcounter/reqcounter.go
  legacy/timewrapper/timewrapper.go
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/feature, lgtm, release-note, sig/release, size/M, wg/k8s-infra

#373 Modified FakeTime to allow advances in time.
  legacy/timewrapper/timewrapper.go
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/feature, lgtm, release-note, sig/release, size/M, wg/k8s-infra

#374 Revert "Modified FakeTime to allow advances in time."
  legacy/timewrapper/timewrapper.go
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/regression, lgtm, release-note, sig/release, size/M, wg/k8s-infra

#376 Abstract a request counter's cycle logic from watch()
  legacy/reqcounter/reqcounter.go
  legacy/reqcounter/reqcounter_test.go
  legacy/timewrapper/timewrapper.go
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/design, kind/feature, lgtm, release-note, sig/release, size/M, wg/k8s-infra

#381 Enable verbose log lvl when passing --verbose flag
  legacy/audit/auditor.go
  legacy/audit/types.go
  legacy/cli/audit.go
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/bug, lgtm, release-note, sig/release, size/S, wg/k8s-infra

#377 Automated testing structure for TestCycle
  legacy/reqcounter/reqcounter_test.go
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/design, kind/feature, lgtm, release-note, sig/release, size/M, wg/k8s-infra

#382 Add support for persistent request counters
  legacy/reqcounter/reqcounter.go
  legacy/reqcounter/reqcounter_test.go
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/feature, lgtm, release-note, sig/release, size/M, wg/k8s-infra

#383 Create multiple request counters
  legacy/reqcounter/reqcounter.go
  legacy/reqcounter/reqcounter_test.go
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/feature, lgtm, release-note, sig/release, size/M, wg/k8s-infra

#384 Adding request counter threshold
  legacy/reqcounter/reqcounter.go
  legacy/reqcounter/reqcounter_test.go
Labels: approved, area/artifacts, area/release-eng, cncf-cla: yes, kind/feature, lgtm, release-note, sig/release, size/L, wg/k8s-infra
