Repository kubernetes-sigs/promo-tools, pull requests merged in 2022-06, with the labels that each got.

#562 update release-* dependencies
  go.mod
  go.sum
Labels: cncf-cla: yes, size/L, approved, lgtm, priority/critical-urgent, release-note, sig/release, area/release-eng, area/artifacts

#564 update release-sdk/utils dependencies
  go.mod
  go.sum
Labels: kind/feature, cncf-cla: yes, size/L, approved, lgtm, release-note, sig/release, area/release-eng, area/artifacts

#568 Perform signing and verification operations in parallel
  go.mod
  go.sum
  internal/legacy/dockerregistry/inventory.go
  internal/promoter/image/sign.go
  promoter/image/imagefakes/fake_promoter_implementation.go
  promoter/image/promoter.go
Labels: cncf-cla: yes, approved, lgtm, size/XL, kind/cleanup, release-note, sig/release, area/release-eng, area/artifacts

#573 v3.4.3 release prep
  VERSION
  cloudbuild.yaml
  dependencies.yaml
  workspace_status.sh
Labels: cncf-cla: yes, release-note-none, approved, lgtm, kind/cleanup, size/S, sig/release, area/release-eng, area/artifacts

#576 Filter unique references in promotion candidates
  internal/promoter/image/sign.go
Labels: kind/bug, cncf-cla: yes, approved, lgtm, size/S, release-note, sig/release, area/release-eng, area/artifacts

#583 Switch to golang native error wrapping
  cmd/kpromo/cmd/cip/audit.go
  cmd/kpromo/cmd/cip/cip.go
  cmd/kpromo/cmd/gh/gh.go
  cmd/kpromo/cmd/manifest/files.go
  cmd/kpromo/cmd/manifest/validate.go
  cmd/kpromo/cmd/pr/pr.go
  cmd/kpromo/cmd/run/files.go
  go.mod
  image/image.go
  internal/legacy/cli/audit.go
  internal/legacy/dockerregistry/inventory.go
  internal/promoter/image/imagepromotion.go
  internal/promoter/image/impl.go
  internal/promoter/image/securityscan.go
  internal/promoter/image/sign.go
  internal/promoter/image/snapshot.go
  test-e2e/cip/e2e.go
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm, kind/cleanup, sig/release, area/release-eng, area/artifacts

#585 Default --image and --digest to null list
  cmd/kpromo/cmd/pr/pr.go
Labels: kind/bug, cncf-cla: yes, approved, lgtm, size/XS, release-note, sig/release, area/release-eng, area/artifacts
