Repository kubernetes-sigs/promo-tools, pull requests merged in 2022-02, with the labels that each got.

#492 Add `ok-to-test` label to dependabot PRs
  .github/dependabot.yml
Labels: cncf-cla: yes, release-note-none, approved, lgtm, kind/cleanup, size/XS, sig/release, area/release-eng, area/artifacts

#498 Verify signatures in candidate images before accepting them from staging
  go.mod
  go.sum
  internal/promoter/image/sign.go
  promoter/image/imagefakes/fake_promoter_implementation.go
  promoter/image/promoter.go
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/XXL, release-note, sig/release, area/release-eng, area/artifacts

#505 Implement sc.ReadRegistries in GGCR
  go.mod
  go.sum
  internal/promoter/image/snapshot.go
  legacy/dockerregistry/inventory.go
Labels: cncf-cla: yes, size/L, approved, lgtm, kind/cleanup, release-note, sig/release, area/release-eng, area/artifacts

#507 Move `cip-mm` to `kpromo mm`
  Makefile
  cmd/cip-mm/README.md
  cmd/kpromo/cmd/mm/mm.go
  cmd/kpromo/cmd/pr/pr.go
  cmd/kpromo/cmd/root.go
  docs/promotion-pull-requests.md
Labels: cncf-cla: yes, size/L, approved, lgtm, kind/cleanup, release-note, sig/release, kind/deprecation, area/release-eng, area/artifacts

#493 kpromo pr: Allow sorting output manifest by tags instead of digest
  go.mod
  image/image.go
  image/image_test.go
Labels: kind/feature, cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash, release-note, sig/release, area/release-eng, area/artifacts

#509 Support multiple images, tags, or digests when growing image manifests
  cmd/kpromo/cmd/mm/mm.go
  cmd/kpromo/cmd/pr/pr.go
  image/manifest/manifest.go
  image/manifest/manifest_test.go
  image/manifest/testdata/empty/non-manifest.txt
  image/manifest/testdata/singleton/images/a/images.yaml
  image/manifest/testdata/singleton/manifests/a/promoter-manifest.yaml
  legacy/dockerregistry/types.go
Labels: kind/feature, cncf-cla: yes, size/L, approved, lgtm, kind/cleanup, release-note, sig/release, area/release-eng, area/artifacts

#512 dockerregistry: Initial refactor to reduce package complexity
  image/manifest/manifest.go
  image/manifest/manifest_test.go
  internal/legacy/audit/auditor.go
  internal/legacy/audit/auditor_test.go
  internal/legacy/audit/types.go
  internal/legacy/dockerregistry/checks.go
  internal/legacy/dockerregistry/checks_test.go
  internal/legacy/dockerregistry/inventory.go
  internal/legacy/dockerregistry/inventory_test.go
  internal/legacy/dockerregistry/registry/context.go
  internal/legacy/dockerregistry/registry/registry.go
  internal/legacy/dockerregistry/registry/set.go
  internal/legacy/dockerregistry/schema/manifest.go
  internal/legacy/dockerregistry/types.go
  internal/legacy/remotemanifest/fake.go
  internal/legacy/remotemanifest/git.go
  internal/legacy/remotemanifest/types.go
  internal/promoter/image/imagepromotion.go
  internal/promoter/image/impl.go
  internal/promoter/image/snapshot.go
  promoter/image/imagefakes/fake_promoter_implementation.go
  promoter/image/promoter.go
  test-e2e/cip-auditor/cip-auditor-e2e.go
  test-e2e/cip/e2e.go
Labels: cncf-cla: yes, approved, lgtm, kind/cleanup, size/XXL, release-note, sig/release, area/release-eng, area/artifacts
