Repository kubernetes-sigs/promo-tools, pull requests merged in 2022-04, with the labels that each got.

#528 reduce logging verbosity
  internal/promoter/image/sign.go
Labels: cncf-cla: yes, release-note-none, approved, lgtm, kind/cleanup, size/XS, sig/release, area/release-eng, area/artifacts

#527 kpromo pr: Support for non-SemVer image tags
  cmd/kpromo/cmd/pr/pr.go
Labels: kind/bug, cncf-cla: yes, approved, lgtm, ok-to-test, size/XS, release-note, sig/release, area/release-eng, area/artifacts

#530 Bump sigs.k8s.io/release-sdk to v0.7.0
  go.mod
  go.sum
Labels: cncf-cla: yes, release-note-none, approved, lgtm, kind/cleanup, size/XS, sig/release, area/release-eng, area/artifacts

#529 Add `latest-canary` image tag and manifests for canary promotion jobs
  canary/images/k8s-staging-bom/images.yaml
  canary/manifests/k8s-staging-bom/promoter-manifest.yaml
  cloudbuild.yaml
  hack/cip-image.sh
Labels: kind/feature, cncf-cla: yes, release-note-none, approved, lgtm, size/S, sig/release, area/release-eng, area/artifacts

#531 Move canary builds to run with main svc account
  canary/manifests/k8s-staging-bom/promoter-manifest.yaml
Labels: cncf-cla: yes, release-note-none, approved, lgtm, kind/cleanup, size/XS, sig/release, area/release-eng, area/artifacts

#532 Update signer account address
  promoter/image/options/options.go
Labels: cncf-cla: yes, release-note-none, approved, lgtm, kind/cleanup, size/XS, sig/release, area/release-eng, area/artifacts

#534 Update release-sdk to v0.8.0
  go.mod
  go.sum
  hack/verify-go-mod.sh
Labels: cncf-cla: yes, approved, lgtm, size/XL, kind/cleanup, release-note, sig/release, area/release-eng, area/artifacts

#535 Add second registry to test sig copies
  canary/manifests/k8s-staging-bom/promoter-manifest.yaml
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/XS, release-note, sig/release, area/release-eng, area/artifacts

#537 Pull sigs.k8s.io/release-sdk@HEAD to pickup retry fix
  go.mod
  go.sum
Labels: kind/bug, cncf-cla: yes, release-note-none, approved, lgtm, size/XS, sig/release, area/release-eng, area/artifacts

#541 Add sigstore test image to canary promotion
  canary/images/sigstore/images.yaml
  canary/manifests/sigstore/promoter-manifest.yaml
Labels: cncf-cla: yes, approved, lgtm, kind/cleanup, size/XS, release-note, sig/release, area/release-eng, area/artifacts

#542 Preserve original signatures from promoted images
  internal/promoter/image/sign.go
Labels: kind/feature, cncf-cla: yes, size/M, approved, lgtm, release-note, sig/release, area/release-eng, area/artifacts

#538 v3.4.1: Release prep
  RELEASE.md
  VERSION
  cloudbuild.yaml
  cmd/cip-mm/README.md
  dependencies.yaml
  workspace_status.sh
Labels: kind/bug, cncf-cla: yes, kind/documentation, size/L, release-note-none, approved, lgtm, kind/cleanup, sig/release, area/release-eng, area/artifacts

#548 build(deps): bump google.golang.org/api from 0.74.0 to 0.75.0
  dependencies.yaml
  go.mod
  go.sum
  hack/verify-golangci-lint.sh
  image/manifest/manifest.go
  internal/legacy/dockerregistry/checks.go
  internal/legacy/dockerregistry/inventory.go
  internal/legacy/dockerregistry/inventory_test.go
  internal/legacy/gcloud/token.go
  promobot/hash.go
  promobot/promotefiles.go
  promoter/file/filestore.go
  promoter/file/gcs.go
  promoter/file/manifest.go
  test-e2e/cip/e2e.go
Labels: kind/feature, cncf-cla: yes, size/L, release-note-none, approved, lgtm, kind/cleanup, sig/release, area/release-eng, area/artifacts
