Repository kubernetes-sigs/promo-tools, pull requests merged in 2022-03, with the labels that each got.

#513 Implement non-recursive ReadRegistry in GGCR
  internal/legacy/dockerregistry/checks.go
  internal/legacy/dockerregistry/inventory.go
  internal/legacy/dockerregistry/inventory_test.go
  internal/legacy/dockerregistry/types.go
  internal/promoter/image/imagepromotion.go
  test-e2e/cip-auditor/cip-auditor-e2e.go
  test-e2e/cip/e2e.go
Labels: cncf-cla: yes, size/L, approved, lgtm, kind/cleanup, release-note, sig/release, area/release-eng, area/artifacts

#501 Sign container images
  cmd/kpromo/cmd/cip/cip.go
  go.mod
  go.sum
  internal/legacy/dockerregistry/inventory.go
  internal/legacy/gcloud/token.go
  internal/promoter/image/sign.go
  internal/promoter/image/sign_test.go
  promoter/image/imagefakes/fake_promoter_implementation.go
  promoter/image/options/options.go
  promoter/image/promoter.go
  test-e2e/cip/e2e.go
Labels: kind/feature, cncf-cla: yes, approved, lgtm, size/XL, release-note, sig/release, area/release-eng, area/artifacts

#522 Fix build date format for `version` subcommands
  Makefile
Labels: kind/bug, cncf-cla: yes, approved, lgtm, size/XS, release-note, sig/release, area/release-eng, area/artifacts

#524 test-e2e: Use *.gcr.io/k8s-cip-test-prod/e2e as the test prod endpoints
  test-e2e/cip/fixture/recursive-thin/manifests/bar/promoter-manifest.yaml
  test-e2e/cip/fixture/recursive-thin/manifests/foo/promoter-manifest.yaml
  test-e2e/cip/fixture/sanity/promoter-manifest.yaml
  test-e2e/cip/tests.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm, kind/cleanup, sig/release, area/release-eng, area/artifacts
