Repository kubernetes-sigs/promo-tools, pull requests merged in 2022-11, with the labels that each got.

#661 Take digests into account for prow diff
  image/manifest/manifest.go
  internal/legacy/cli/run.go
  internal/legacy/dockerregistry/schema/manifest.go
  internal/legacy/dockerregistry/schema/manifest_test.go
  promoter/image/promoter.go
Labels: kind/feature, cncf-cla: yes, size/L, approved, lgtm, release-note, sig/release, area/release-eng, area/artifacts

#663 releng: Bump promoter to v3.4.8
  VERSION
  cloudbuild.yaml
  dependencies.yaml
  workspace_status.sh
Labels: kind/feature, cncf-cla: yes, release-note-none, approved, lgtm, size/S, sig/release, area/release-eng, area/artifacts

#665 Remove unused `kpromo cip --threads` flag
  cmd/kpromo/cmd/cip/cip.go
Labels: cncf-cla: yes, approved, lgtm, kind/cleanup, size/XS, release-note, sig/release, area/release-eng, area/artifacts

#667 Update golangci-lint and config
  .golangci.yml
  api/files/manifest_test.go
  cmd/count-requests/main.go
  cmd/kpromo/cmd/cip/cip.go
  cmd/kpromo/cmd/manifest/files.go
  cmd/verify-gcr-quota/main.go
  dependencies.yaml
  hack/verify-golangci-lint.sh
  image/image_test.go
  internal/legacy/audit/auditor.go
  internal/legacy/cli/audit.go
  internal/legacy/dockerregistry/checks.go
  internal/legacy/dockerregistry/checks_test.go
  internal/legacy/dockerregistry/inventory.go
  internal/legacy/dockerregistry/inventory_test.go
  internal/legacy/dockerregistry/registry/registry.go
  internal/legacy/dockerregistry/registry/set.go
  internal/legacy/dockerregistry/schema/manifest.go
  internal/legacy/remotemanifest/git.go
  internal/legacy/stream/http.go
  internal/promoter/image/snapshot.go
  promobot/hash_test.go
  promoter/file/interfaces.go
  test-e2e/cip-auditor/cip-auditor-e2e.go
  test-e2e/cip/e2e.go
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm, kind/cleanup, sig/release, area/release-eng, area/artifacts

#666 Switch to golang 1.19
  Dockerfile
  dependencies.yaml
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm, kind/cleanup, release-note, sig/release, area/release-eng, area/artifacts

#668 use bullseye golang image
  Dockerfile
  dependencies.yaml
Labels: cncf-cla: yes, release-note-none, approved, lgtm, kind/cleanup, size/XS, sig/release, area/release-eng, area/artifacts

#674 Dedup images to verify for signed edges
  internal/promoter/image/sign.go
Labels: kind/bug, cncf-cla: yes, approved, lgtm, size/XS, release-note, sig/release, area/release-eng, area/artifacts

#681 Create a new signer after getting the identity token
  internal/promoter/image/sign.go
Labels: kind/bug, cncf-cla: yes, approved, lgtm, size/XS, release-note, sig/release, area/release-eng, area/artifacts

#684 Add a new issue template for cutting releases
  .github/ISSUE_TEMPLATE/cut-release.md
Labels: cncf-cla: yes, kind/documentation, release-note-none, approved, lgtm, size/S, sig/release, area/release-eng, area/artifacts

#683 releng: Bump promoter to v3.4.10
  VERSION
  cloudbuild.yaml
  dependencies.yaml
  workspace_status.sh
Labels: kind/feature, cncf-cla: yes, release-note-none, approved, lgtm, size/S, sig/release, area/release-eng, area/artifacts
