Repository kubernetes-sigs/promo-tools, pull requests merged in 2023-02, with the labels that each got.

#718 s3 copying: use bucket region
  promoter/file/s3.go
Labels: cncf-cla: yes, size/M, approved, lgtm, release-note, sig/release, area/release-eng, area/artifacts

#722 S3 promotion: support anonymous authentication
  cmd/kpromo/cmd/run/files.go
  promoter/file/s3.go
Labels: cncf-cla: yes, approved, lgtm, size/S, release-note, sig/release, area/release-eng, area/artifacts

#731 releng: Bump promoter to v3.4.12
  VERSION
  cloudbuild.yaml
  dependencies.yaml
  workspace_status.sh
Labels: kind/feature, cncf-cla: yes, release-note-none, approved, lgtm, size/S, sig/release, area/release-eng, area/artifacts

#740 Add remaining AR Regions
  docker/config.json
Labels: cncf-cla: yes, approved, lgtm, size/S, release-note, sig/release, area/release-eng, area/artifacts

#745 kpromo sigcheck: Verify and fix missing image signatures
  cmd/kpromo/cmd/root.go
  cmd/kpromo/cmd/sigcheck/sigcheck.go
  internal/promoter/image/signcheck.go
  promoter/image/checkresults/checkresults.go
  promoter/image/imagefakes/fake_promoter_implementation.go
  promoter/image/options/options.go
  promoter/image/promoter.go
Labels: kind/feature, cncf-cla: yes, approved, lgtm, tide/merge-method-squash, size/XL, release-note, sig/release, area/release-eng, area/artifacts
