Repository kubernetes-sigs/promo-tools, pull requests merged in 2023-04, with the labels that each got.

#807 Switched from N1 to E2 machine
  cloudbuild.yaml
Labels: cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test, kind/cleanup, size/XS, sig/release, area/release-eng, area/artifacts

#817 Rate limiter: Drop QPS to 50
  promoter/image/ratelimit/roundtripper.go
Labels: cncf-cla: yes, approved, lgtm, kind/cleanup, size/XS, release-note, sig/release, area/release-eng, area/artifacts

#809 Replicate signatures just once
  internal/promoter/image/sign.go
  promoter/image/imagefakes/fake_promoter_implementation.go
  promoter/image/promoter.go
  promoter/image/promoter_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, kind/cleanup, release-note, sig/release, area/release-eng, area/artifacts

#811 Bump kpromo versions to v3.5.2
  VERSION
  cloudbuild.yaml
  dependencies.yaml
  workspace_status.sh
Labels: cncf-cla: yes, kind/documentation, release-note-none, approved, lgtm, size/S, sig/release, area/release-eng, area/artifacts
