Repository kubernetes-sigs/promo-tools, pull requests merged in 2024-04, with the labels that each got.

#1262 Upgrade go to 1.22
  .golangci.yml
  Dockerfile
  api/files/validation.go
  cmd/kpromo/cmd/cip/audit.go
  cmd/kpromo/cmd/cip/cip.go
  cmd/kpromo/cmd/gh/gh.go
  cmd/kpromo/cmd/manifest/files.go
  cmd/kpromo/cmd/mm/mm.go
  cmd/kpromo/cmd/pr/pr.go
  cmd/kpromo/cmd/run/files.go
  cmd/kpromo/cmd/sigcheck/sigcheck.go
  dependencies.yaml
  go.mod
  hack/verify-golangci-lint.sh
  internal/legacy/audit/auditor_test.go
  internal/legacy/cli/audit.go
  internal/legacy/cli/run.go
  internal/legacy/dockerregistry/checks.go
  internal/legacy/dockerregistry/inventory.go
  internal/legacy/dockerregistry/inventory_test.go
  internal/legacy/dockerregistry/schema/manifest.go
  internal/legacy/gcloud/token.go
  internal/legacy/reqcounter/reqcounter_test.go
  internal/legacy/stream/http.go
  internal/promoter/image/signcheck.go
  internal/promoter/image/snapshot.go
  promobot/promotefiles.go
  promoter/file/s3.go
  promoter/image/promoter_test.go
  test-e2e/cip-auditor/cip-auditor-e2e.go
  test-e2e/cip/e2e.go
Labels: kind/feature, cncf-cla: yes, size/L, approved, lgtm, kind/cleanup, release-note, sig/release, area/release-eng, area/artifacts

#1279 Updating promotion-pull-requests.md to reflect that build admins no longer need to cut packages for official releases
  docs/promotion-pull-requests.md
Labels: cncf-cla: yes, kind/documentation, release-note-none, approved, lgtm, kind/cleanup, size/XS, sig/release, area/release-eng, area/artifacts

#1282 remove listx from OWNERS_ALIASES
  OWNERS_ALIASES
Labels: cncf-cla: yes, release-note-none, approved, lgtm, kind/cleanup, size/XS, sig/release, area/release-eng, area/artifacts
